name: newsd
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  retrofit: ^4.4.1
  dio: ^5.7.0
  flutter_bloc: ^8.1.2
  get_it: ^8.0.0
  floor: ^1.4.1
  equatable: ^2.0.5
  awesome_dio_interceptor: ^1.2.0
  google_fonts: ^6.2.1
  very_good_analysis: ^6.0.0
  go_router: ^14.3.0
  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  retrofit_generator: ^9.1.2
  build_runner: ^2.3.3
  floor_generator: ^1.4.1

flutter:
  uses-material-design: true
  generate: true
